comment_width = 100
edition = "2018"
error_on_line_overflow = true
error_on_unformatted = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 120
merge_imports = true
normalize_comments = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
