sudo: required
language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

os:
  - linux
  # - osx
  # - windows

addons:
  apt:
    packages:
      - libssl-dev

cache:
  directories:
    - $HOME/.cargo

branches:
  only:
    - master

env:
 global:
   - RUST_BACKTRACE=1

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

before_script:
  - rustup component add clippy-preview
  - rustup component add rustfmt

script:
  # Have rustfmt exit with error code if input is not formatted correctly.
  - cargo fmt --all -- --check
  - cargo build --verbose
  - cargo doc --verbose
  - cargo test --locked --verbose
  - cargo clippy --all-targets --all-features #  -D warnings

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
